services:
  # 1. Database Service (PostgreSQL)
- type: pserv
  name: my-app-db
  plan: free # Use 'standard' for production or higher loads
  env: postgres
  # A start command is needed for Render to create the database
  # and output the internal connection URL.
  startCommand: sh start.sh # Create a dummy start script if needed, or leave blank if using a dummy file.
  
  # 2. Web Service (Django/Gunicorn)
- type: web
  name: my-django-app
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn 6ecom_django.wsgi:application"
  # Replace 'your_project_name' with your actual Django project name
  
  # Environment variables for the web service
  envVars:
    - key: DATABASE_URL
      fromService:
        type: pserv
        name: my-app-db
        property: connectionString
    - key: PYTHON_VERSION
      value: 3.11.8 # Set this to your desired Python version
    - key: DJANGO_SECRET_KEY # IMPORTANT: Replace this with your actual, secure key
      value: a-very-long-and-secure-random-key
    - key: WEB_CONCURRENCY
      value: 4 # Number of Gunicorn workers (adjust based on your plan)
    - key: DISABLE_COLLECTSTATIC
      value: 0 # Render will run collectstatic automatically