services:
  - type: web
    name: your-django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject_ecom.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject_ecom.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
